requires 'perl', '5.014000';
requires 'parent';
requires 'Moose', '2.0000';
requires 'Moops', '0.034';
requires 'Dist::Zilla';
requires 'Safe::Isa';
requires 'File::chdir';
requires 'Git::Wrapper';
requires 'MooseX::AttributeDocumented';
requires 'MooseX::AttributeShortcuts';
requires 'MooseX::StrictConstructor';
requires 'Types::Standard';
requires 'Types::Path::Tiny';
requires 'DateTime';
requires 'YAML::Tiny';
requires 'File::ShareDir';
requires 'Dist::Zilla', '5.000';
requires 'Config::INI';
requires 'List::AllUtils';
requires 'Path::Tiny';
requires 'Pod::Weaver::Config::Assembler';
requires 'namespace::autoclean';
requires 'PerlX::Maybe';
requires 'Module::Load';
requires 'Carp';

on develop => sub {
    requires 'Dist::Zilla::Plugin::PodWeaver', '4.000';

    requires 'Dist::Zilla::Role::PluginBundle::Easy';
    requires 'Dist::Zilla::Role::PluginBundle::PluginRemover';
    requires 'Dist::Zilla::Role::PluginBundle::Config::Slicer';
    requires 'Dist::Zilla::Plugin::Git::GatherDir';
    requires 'Dist::Zilla::Plugin::CopyFilesFromBuild';
    requires 'Dist::Zilla::Plugin::ReversionOnRelease';
    requires 'Dist::Zilla::Plugin::OurPkgVersion';
    requires 'Dist::Zilla::Plugin::NextRelease';
    requires 'Dist::Zilla::Plugin::PreviousVersion::Changelog';
    requires 'Dist::Zilla::Plugin::NextVersion::Semantic';
    requires 'Dist::Zilla::Plugin::Git::Check';
    requires 'Dist::Zilla::Plugin::GithubMeta';
    requires 'Dist::Zilla::Plugin::ReadmeAnyFromPod';
    requires 'Dist::Zilla::Plugin::MetaNoIndex';
    requires 'Dist::Zilla::Plugin::Prereqs::FromCPANfile';
    requires 'Dist::Zilla::Plugin::ModuleBuildTiny';
    requires 'Dist::Zilla::Plugin::MetaJSON';
    requires 'Dist::Zilla::Plugin::ContributorsFromGit';
    requires 'Dist::Zilla::Plugin::PodSyntaxTests';
    requires 'Dist::Zilla::Plugin::MetaYAML';
    requires 'Dist::Zilla::Plugin::License';
    requires 'Dist::Zilla::Plugin::ExtraTests';
    requires 'Dist::Zilla::Plugin::ShareDir';
    requires 'Dist::Zilla::Plugin::Manifest';
    requires 'Dist::Zilla::Plugin::ManifestSkip';
    requires 'Dist::Zilla::Plugin::CheckChangesHasContent';
    requires 'Dist::Zilla::Plugin::TestRelease';
    requires 'Dist::Zilla::Plugin::ConfirmRelease';
    requires 'Dist::Zilla::Plugin::UploadToCPAN';
    requires 'Dist::Zilla::Plugin::MetaProvides::Class';
    requires 'Dist::Zilla::Plugin::MetaProvides::Package';
    requires 'Dist::Zilla::Plugin::Git::Commit';
    requires 'Dist::Zilla::Plugin::Git::Tag';
    requires 'Dist::Zilla::Plugin::Git::Push';
    requires 'Dist::Zilla::Plugin::PodnameFromFilename';
    requires 'Pod::Elemental::Transformer::List';
    requires 'Pod::Weaver::Plugin::SingleEncoding';
    requires 'Pod::Weaver::Plugin::Transformer';
    requires 'Pod::Weaver::PluginBundle::CorePrep';
    requires 'Pod::Weaver::Section::Authors';
    requires 'Pod::Weaver::Section::Collect';
    requires 'Pod::Weaver::Section::Generic';
    requires 'Pod::Weaver::Section::Homepage::DefaultCPAN';
    requires 'Pod::Weaver::Section::Leftovers';
    requires 'Pod::Weaver::Section::Legal';
    requires 'Pod::Weaver::Section::Name';
    requires 'Pod::Weaver::Section::Region';
    requires 'Pod::Weaver::Section::Source::DefaultGitHub';
    requires 'Pod::Weaver::Section::Version';
    requires 'Test::More', '0.96';
    requires 'Test::Pod';

};


on test => sub {
    requires 'Test::Differences';
    requires 'Test::More', '0.96';
    requires 'syntax';
    requires 'Syntax::Feature::Qs';
};
