+doctype: dist

+prereqs:
  develop:
    requires:
      - This::Thing

+plugins:
 - +plugin: GatherDir

 - +plugin: PruneCruft

 - +plugin: ManifestSkip
   +remove_if: $self.no_manifest_skip

 - +plugin: PodWeaver
   +remove_if: $self.is_task

 - +plugin: TaskWeaver
   +add_if: $self.is_task

 - +plugin: MetaYAML

 - +plugin: License

 - +plugin: Readme
   root: yes
   more_root: no
   suffix: txt
   headings:
   - head1

 - +plugin: ExtraTests

 - +plugin: ExecDir
   dir: script

 - +plugin: ShareDir

 - +plugin: MakeMaker

 - +plugin: Manifest

 - +plugin: TestRelease

 - +plugin: ConfirmRelease
   default: $self.confirm_release
   prompt: $self.prompt

 - +plugin: UploadToCPAN

---

+doctype: weaver

+plugins:
 - +plugin: '@CorePrep'

 - +plugin: -SingleEncoding

 - +plugin: Name

 - +plugin: Version

 - +plugin: prelude
   +base: Region

 - +plugin: Synopsis
   +base: Generic

 - +plugin: Description
   +base: Generic

 - +plugin: Overview
   +base: Generic

 - +plugin: Attributes
   +base: Collect
   command: attr
   header: ATTRIBUTES

 - +plugin: Methods
   +base: Collect
   command: method
   header: METHODS

 - +plugin: Functions
   +base: Collect
   command: func
   header: FUNCTIONS

 - +plugin: Leftovers

 - +plugin: postlude
   +base: Region

 - +plugin: Authors

 - +plugin: Legal

 - +plugin: List
   +base: -Transformer
   +in: Elemental
   transformer: List