#!perl
use strict;
use warnings;

use Dist::Iller::Builder;

# VERSION
# PODNAME: iller

my $builder = Dist::Iller::Builder->new->parse;
$builder->generate_dist_ini if defined $builder;
$builder->generate_weaver_ini if defined $builder;

system('dzil', @ARGV);

__END__
