#!perl
use 5.10.1;
use strict;
use warnings;

use Dist::Iller;

# PODNAME: iller
our $VERSION = '0.1401';

my $iller = Dist::Iller->new;
$iller->parse;
$iller->generate_files;

system('dzil', @ARGV);

__END__
