#!perl
use 5.10.1;
use strict;
use warnings;

use Dist::Iller;

# PODNAME: iller
our $VERSION = '0.1405';

my $iller = Dist::Iller->new;
$iller->parse;
$iller->generate_files('before');

system('dzil', @ARGV);

$iller->generate_files('after');

__END__
